### ISSUE TITLE
Align with latest EPUB 3.0.1 changes

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#1]

**Comment by josteinaj** [comment]
[EPUB 3.0.1 Changes from EPUB 3.0](http://www.idpf.org/epub/301/spec/epub-changes.html) with regards to "DAISY 2.02 to EPUB3":
- 2.3: Although 3.0.1 lists some recognized `dc:type`s,
  none of them are implicit for this conversion and 3.0.1
  does not prohibit the use of any other types.
  So nothing needs to be changed here.
- 3.5: aria-describedat is the responsibility of
  `html-upgrade.xsl` or the future `px:epub3-enhance`.
  `longdesc` is re-added to HTML5 anyway, so
  aria-describedat isn't really necessary.
  Nothing to fix here.
- 4.1: "no longer valid for Renditions of different
  EPUB Publications to be bundled together"; this
  implies that we can't convert "Multiple DTB volume"
  DAISY 2.02 filesets to a single EPUB3. However, this
  wasn't supported in the converter anyway, so no
  changes are needed.
- 6: No new class-type mappings
  (the only DAISY 2.02 class without a mapping is "group").

So there's no changes needed for daisy202-to-epub3 as I can see. But I think we identified a couple of issues at the face-to-face, didn't we?

**Comment by rdeltour** [comment]
> 2.3: Although 3.0.1 lists some recognized dc:types, none of them are implicit for this conversion and 3.0.1 does not prohibit the use of any other types. So nothing needs to be changed here.

OK.

> 3.5: aria-describedat is the responsibility of html-upgrade.xsl or the future px:epub3-enhance. longdesc is re-added to HTML5 anyway, so aria-describedat isn't really necessary. Nothing to fix here.

Right. `html-upgrade.xsl` passes through all `aria-*` attributes. And the refactored image description conversion due in #3 will take care of proper use of it.

> 4.1: "no longer valid for Renditions of different EPUB Publications to be bundled together"; this implies that we can't convert "Multiple DTB volume" DAISY 2.02 filesets to a single EPUB3. However, this wasn't supported in the converter anyway, so no changes are needed.

OK about no changes needed. But in any case I would think that multi-volume DAISY 2.02 would be converted in a single EPUB 3 Rendition anyway (i.e. just a regular EPUB 3). Multi Renditions are for e.g. different screen sizes, layout types (fix/reflow), languages, etc.

> 6: No new class-type mappings (the only DAISY 2.02 class without a mapping is "group").

OK.

> I think we identified a couple of issues at the face-to-face, didn't we?
- 2.1 This is a  significant change, but at first sight I don't think it's relevant in `daisy202-to-epub3`
- 2.5 may require updating the opf-creator metadata processing to support new reserved prefixes

That's all I can see, unless we want to make our EPUB utils super generic but it's not needed at this point.

**Comment by josteinaj** [comment]
Ok. Then I'd say daisy202-to-epub3 is done wrt this issue.
epubcheck-adapter is set to depend on epubcheck 3.0.1, so epub3-validator will support whatever versions of epub that that version of epubcheck supports.

Have you checked zedai-to-epub3 and html-to-epub3?

**Comment by rdeltour** [comment]
> I'd say daisy202-to-epub3 is done wrt this issue.

OK, good.

> Have you checked zedai-to-epub3 and html-to-epub3?

Not yet.
