### ISSUE TITLE
Reorganize the framework's modules

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#10]
As agreed at the Paris f2f:
- calabash-adapter
  - all s/b internal except XProcStepProvider
  - => major++
- calabash-custom-steps
  - all internall
  - => major++
- framework-core
  - org.daisy.converter.parser => org.daisy.script.parser.impl
    - move the constants + parser there
  - move XProcScriptParser to org.daisy.pipeline.script.parser
  - move the DefaultXProcScriptRegistry to impl
  - org.daisy.pipeline.job.fuzzy => internal, move to ____
  - job public
    12345678
    - AbstractJobContext
    - ExecutionQueue
    - Job
    - JobContext
    - JobExecutionService
    - JobId
    - JobManager
    - JobManagerFactory
    - JobMonitor
    - JobMonitorFactory
    - JobResult
    - JobSize
    - JobStorage
    - ResourceCollection/ZipResouceContext => move to common-utils/webservice-utils ?
    - ResultSet
    - ReulstFactory => rename to ResultSetUtils
    - RuntimeConfigurator
    - StatusMessage
    - URIMapper => move to common-utils ?
  - delete ExecutingJobManager
- webservice
  - remove the ctxtfactory ref
- framework persistence
  - Rename o.d.p.p.jobs to o.d.p.p.job
  - Move PersistentJobMonitor\* from persistence => persistence.job
  - o.d.p.p => o.d.p.p.impl (Database.java should be internal)
  - o.d.p.p.jobs => all internal
  - o.d.p.p.messaging => all internal
  - o.d.p.p.services can be deleted, there are no references to EntityManagerProvider
  - o.d.p.p.webservice => all internal
- framework volatile
  - o.d.p.n.Deactivator can be deleted.
  - o.d.p.n.jobs => o.d.p.n.job
  - o.d.p.n.VolatileMonitorFactory => move to o.d.p.n.job
  - all classes are internal
- logging-activator: all internal
- logging-appender: no changes
- modules-api: If we merge modules-api and module tracker all can be marked as internal
- modules-registry: all internal
- persistence-derby: all internal
- persistence-mysql: all internal
- push-notifier: all internal
- webservice: all internal
- webservice-utils
  - o.d.p.webserviceutils: all external
  - o.d.p.w.callback: I've got the feelign that this shouldn't be in this bundle. Maybe core instead, own module?
    - Callback and CallbackRegistry external
    - DefaultCallbackRegistry internal
  - o.d.p.w.requestlog: is this the right bundle?
    - RequestLog extenal
    - RequestLogEntry external
    - SimpleRequestLog internal
  - o.d.p.w.storage: all external (again is this the right bundle?)
  - o.d.p.w.xml: all external
- woodstox-osgi-adapter: all internal
- xmlcatalog:
  - o.d.p.xmlcatalog: external
  - o.d.p.x.stax: internal
- xpath-registry: all external
- xproc-api: all external

See daisy-consortium/pipeline-framework#44

**Comment by capitancambio** [comment]
it's been merged, should I close this?

**Comment by rdeltour** [comment]
> it's been merged, should I close this?

I just marked it as done, we'll close it when we release.

**Comment by capitancambio** [comment]
ok :+1:
