### ISSUE TITLE
Create a simple updater

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#11]
Adopt a simple approach:
- preferably only update to latest version
- only update modules, framework update = increase of assembly's major version = reinstall
  - rationale is that framework bundles need to be updated less
    frequently and that modules should work with any version of
    the framework
  - pitfall: some module updates may depend on 3th-party library
    updates which would not be supported by updater and which
    would cause the major version to increase rapidly.
    Solutions:
    1. threat these 3th party dependencies as modules, or
    2. updater handles all jars. this requires that each BoM
       maps to a single install directory, or that _all_ jars
       are installed in one directory (see design). a new
       installation (and increase of major version) is only
       required when e.g. configuration files change.
- design:
  - some refactoring needs to be done so that all bundles that
    are used in the assembly POM are defined in exactly one BoM,
    and that each BoM maps to exactly one install directory in
    the assembly. See #8.
  - the updater will be implemented as a Java library so that it
    can be used in the web gui, the desktop gui and a command line
    tool
  - update steps
    1. find out which version we are at by looking at config.properties
    2. use sonatype's API to get the latest assembly POM
    3. if that version is newer, parse the assembly POM and
       according BoMs to get the list of artifact we need to
       download
    4. download the artifacts from maven central
    5. remove old versions of jars and install the new versions
    6. update the number in config.properties

**Comment by bertfrees** [comment]
Can be closed?
