### ISSUE TITLE
Update to Calabash 1.1.20 and Saxon 9.8

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#117]
We'd have to make sure that our pipelines still work, since there may be some unexpected changes in base URI handling. More details on Norm’s blog:

https://so.nwalsh.com/2018/01/24/saxon98

**Comment by bertfrees** [comment]
Note that Saxon 9.8 supports some XSLT 3.0 features.

**Comment by bertfrees** [comment]
If I manage to rebase the patches I should also make some PRs so that Norm considers adding the changes (at least to the XProc 3 implementation).

**Comment by bertfrees** [comment]
This is partly done. The braille modules depend on a Saxon package that was removed from 9.8 and I still need to find a solution for that.
