### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#118]
### Part 1
- [x] check if we can run the Pipeline on Java 9
- [x] move to Java 9 as minimum requirement

### Part 2
moved to https://github.com/daisy/pipeline-tasks/issues/127

**Comment by mccallum-sgd** [comment]
> check if we can build with Java 9
I've built with Java 9 and 10 with no problems.

We have moved to Java 9 as the minimum requirement (https://github.com/daisy/pipeline/commit/37346a082c75fd4109d9b011ba1caf9d43150d29).

**Comment by bertfrees** [comment]
PR: https://github.com/daisy/pipeline-assembly/pull/158
