### ISSUE TITLE
Update Calabash and Saxon to recent versions

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#12]
At the time of writing, calasbash 1.0.16 and saxon 9.5.1.5.

@capitancambio please help with the `calabash-adapter` if neeeded.

**Comment by bertfrees** [comment]
see
- https://github.com/daisy/osgi-libs/tree/calabash_v1.0.16
- https://github.com/daisy/osgi-libs/tree/saxon_9.5.1.3
- https://github.com/daisy/pipeline-framework/tree/calabash_v1.0.16

**Comment by capitancambio** [comment]
Weird error, fantastic. I got the following error when mci-ing calabash:
/home/javi/daisy/osgi-libs/calabash/target/calabash/src/com/xmlcalabash/piperack/Status.java:41:
error: unmappable character for encoding ASCII
        tree.addText("?? 2007-2013 Norman Walsh");

if I go to the target/calabash folder and run ./ant everything works as a
charm, (of course my locale is utf-8) it seems that it gets changed
somewhere by maven. The errors still stares at me uninterested after
following several advices from google

any bells?

cheers,

Javi

**Comment by bertfrees** [comment]
No bells. Are you trying to compile 1.0.16 (my branch) or 1.0.18?

**Comment by capitancambio** [comment]
your branch

cheers,

Javi

**Comment by bertfrees** [comment]
Have you tried changing the build.xml to explicitly say that the source is UTF-8-encoded? Add something like this (haven't tested):

``` xml
<presetdef name="javac">
   <javac>
      <compilerarg line="-encoding utf-8"/>
   </javac>
</presetdef>
```

or

``` xml
<presetdef name="javac">
   <javac>
      <sysproperty key="file.encoding" value="UTF-8" />
   </javac>
</presetdef>
```
