### ISSUE TITLE
Review the EPUB 3.2 specs and identify the required changes

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#125]
[EPUB 3.2](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html) is being finalized, we should review the specs and identify whatever needs to be changed or improved in our production scripts.

**Comment by NPavie** [comment]
Following the [EPUB 3.2 changes](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-changes.html) document, I identified the following changes to do on identified files : 

- There are 2 new entry to add in the [extension to mediatype mapping](https://github.com/daisy/pipeline/blob/master/modules/common/mediatype-utils/src/main/resources/xml/maps/ext-to-mediatype.xml) file : 
`<entry key="sfnt" value="application/font-sfnt"/>`
`<entry key="woff2"  value="font/woff2"/>`

- A warning can be added in [create-metadata.merge.xsl](https://github.com/daisy/pipeline/blob/master/modules/scripts-utils/epub3-pub-utils/src/main/resources/xml/xproc/create-metadata.merge.xsl) to warn the user about the presence of the following metadata properties : 
  - `display-seq` is deprecated (precedence follows the document order).
  - `meta-auth` is deprecated.
    - For a `<dc:subject id="subjectID" />` element, authority and term can now be assigned using the following metadata : 
      - `<meta refines="#subjectID" property="authority">`[registered authority value](https://idpf.github.io/epub-registries/authorities/)`</meta>`
      - `<meta refines="#subjectID" property="term">term or code defined by the corresponding authority to identify the subject</meta>`

- For the new `<link />` relationship values (found in files [create-metadata.merge.xsl](https://github.com/daisy/pipeline/blob/master/modules/scripts-utils/epub3-pub-utils/src/main/resources/xml/xproc/create-metadata.merge.xsl) and [zedai-to-metadata.xsl](https://github.com/daisy/pipeline/blob/master/modules/scripts-utils/metadata-utils/src/main/resources/xml/zedai-to-metadata.xsl)) : 
  - the values `marc21xml-record`, `mods-record`, `onix-record`, and `xmp-signature` should be replaced by the value `record`, in association with : 
    - an attribute `media-type` with a corresponding media-type value, 
    - and, for `rel="onix-record"` and `rel="xmp-signature"`, a new attribute `properties` with the value `onyx` or `xmp`.

- `<bindings/>` is deprecated and should be either removed from the generation process or raise a warning message in [create-package-doc.xpl](https://github.com/daisy/pipeline/blob/master/modules/scripts-utils/epub3-pub-utils/src/main/resources/xml/xproc/create-package-doc.xpl)
  - The file [create-package-doc.handler-fileset-to-bindings.xsl](https://github.com/daisy/pipeline/blob/master/modules/scripts-utils/epub3-pub-utils/src/main/resources/xml/xproc/create-package-doc.handler-fileset-to-bindings.xsl) could become obsolete.

On the recommendation for the epub to be compliant with the Epub Accessibility check, it could require an ACE validation module.

**Comment by bertfrees** [comment]
Thanks!

**Comment by NPavie** [comment]
I have done some more code screening and i did not find any supplemental changes required for the epub 3.2 conformance, but i may be lacking some knowledge on the specs of the other formats (there might need some new conversion rules for metadatas that i missed).

I am still doing some testing using the pipeline-samples books and some dtbooks provided by braillenet, with a validation pass using the latest RC version of epubcheck.

I had some warnings and errors during the tests not related to the 3.2 changes :  
- Daisy3 to Epub3 : epubcheck raises a warning on the daisy3 book of the pipeline-samples repo : "EPUB/nav.xhtml(1,680): Avertissement lors de l'analyse du fichier: nav elements should have an epub:type attribute". After checking, the corresponding nav element is a notes navigation list with no epub:type specified in the resulting epub. It has been generated from a simple navlist.
- dtbooks to Epub3 : An epub created from a dtbooks (2005-3) from braillenet raised a dc:title error. In the generated epub, I noticed that a secondary empty dc:title tag, while in the source dtbook I noticed a doctitle tag with an empty span. (After a simple test, I could confirm this doctitle with empty text node translated in an empty dc:title). I was thinking about ignoring the doctitle tag if it does not contain any text node.
- zedai to epub3 : on several tests, epubcheck raises errors in the toc.xhtml file with ol tags missing li sub-tags. An other warning is raised about a missing zedai-mods.xml file.
- html to epub3 : the pipeline pointed me an error on the html sample of the pipeline-samples repo :  link tags were not closed. I retrieved the original source-code from the idpf website to correct this, and the conversion works but epubcheck also raises an error in toc.xhtml.

**Comment by bertfrees** [comment]
Thanks for the extensive testing. For all the issues you mentioned it make sense to fix them in the code (or the samples repo). In addition, I am wondering if we should add optional output validation to all of our scripts. Then, if the input was valid and the output is invalid, we can include a suggestion in the validation report to forward it to us so that we can fix the conversion.

**Comment by NPavie** [comment]
I'm starting the investigations for code corrections.
For the output validation, i think that make sense and the conversion error reporting could greatly help to find unexpected cases. 
I wonder if we should make the error reporting to the devs automatic or ask the user to send the report  (manually or with an option).
Note that a script option could require for the user to re-run the job in error.
For the automatic reporting, we would need to warn the user about it in the user guide or in the console and allow him to disable the sending.

Is there a way for the pipeline to raise a dialog box or to ask an input at the end of a script to ask directly for the sending of the report (and the sources and inputs) if there are errors and warnings ?

**Comment by bertfrees** [comment]
The communication between the user and the script is really one-way. First from the user to the script (job submission) and then from the script to the user (job status, messages, results, reports). The report can contain some JavaScript for more advanced functionality, but that is still limiting, and not really the original purpose of the reports. To properly implement automatic reporting would probably require proper support in the engine and/or GUIs. Let's keep this as an idea for later. A first step would be to add optional output (and [input](https://github.com/daisy/pipeline-scripts/issues/112)) validation to all scripts, and that is already quite a big task.

**Comment by bertfrees** [comment]
I had a look at commit https://github.com/NPavie/pipeline/commit/65e6b807e0c006bb8a42f0af1c2ec51fc53ee7a2. Looks good. I made some comments inline. A test to explain the changes would be nice, especially for html5-outliner.xsl / nav-fixer.xsl.

**Comment by NPavie** [comment]
I'm starting a bit of code cleaning on it (forgot to remove uneffective tests).
As we discussed on slack, i will wrap the html-outliner xslt process in a new xproc step (html-outline.xproc) and add xprocspec tests.
I'll also add some tests for the nav-fixer corrections.
