### ISSUE TITLE
Web UI: support "Option Templates"

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-tasks#13]
# Option Templates

A way to store a set of defaults for option and input values. This is a requirement which has emerged from the nordic braille project.
## Format

Lets use the jobRequest XML grammar to store option sets, and store the job requests and context files in a directory structure (which makes it easy to backup).

Suggested directory structure:

```
webui
├── (...)
└── default-options
    ├── dtbook-to-pef
    │   ├── Braille 6-dot
    │   │   ├── context
    │   │   │   ├── copyright.xml
    │   │   │   └── img
    │   │   │       └── logo.jpg
    │   │   └── jobRequest.xml
    │   └── Braille 8-dot
    │       ├── context
    │       │   ├── copyright.xml
    │       │   └── img
    │       │       └── logo.jpg
    │       └── jobRequest.xml
    └── epub-to-pef
```
## [Jobs library](https://github.com/daisy/pipeline-jobs-java/)
- [x] API for creating/building a job
- [x] store a job
- [x] load a job
- [x] list available stored jobs
- [x] delete a stored job from disk
- [ ] apply a template (i.e. merge one job into another job)
## [Web UI](https://github.com/daisy/pipeline-webui/)
- [x] a separate tab for selecting a template on the job creation page
- [x] ability to delete a template from the template listing tab
- [x] ability to rename a template from the template listing tab
- [x] a button in the options tab for saving option set as template
- [x] when selecting a template; all context files should be loaded from the template, and all the options should be set according to the template
- [x] consider using template name as part of the job nicename
- [x] consider adding a toggle switch to the template listing tab, which switches between personal and shared template
- [ ] a way to change the template after files have been uploaded (i.e. remember which files are template files and which files are uploaded files)
## [Client library](https://github.com/daisy/pipeline-clientlib-java/)
- [ ] use jobs-java for job creation, validation etc. to avoid duplicating too much functionality
## Related issues
- daisy/pipeline-webui#17
- daisy/pipeline-clientlib-java#4
- snaekobbi/sprints#88
- snaekobbi/sprints#89
- snaekobbi/sprints#90
- snaekobbi/sprints#91
- snaekobbi/sprints#94

**Comment by bertfrees** [comment]
Great, thanks Jostein! Another feature could be to filter templates, e.g. on script name. And to select a template even before a script has been chosen.

It's not really clear how "a tab in settings for managing default options" would work.

**Comment by josteinaj** [comment]
> Another feature could be to filter templates, e.g. on script name.

Yes, when creating a job, after selecting a script, the list of templates should be filtered to only show those belonging to the selected script.

> And to select a template even before a script has been chosen.

Hmm, this could be done, but I'm not sure how to present it in a GUI and what the use-case would be.

> It's not really clear how "a tab in settings for managing default options" would work.

I was thinking maybe something like this:
http://imgur.com/UfaVXSc

**Comment by bertfrees** [comment]
> > And to select a template even before a script has been chosen.
> 
> Hmm, this could be done, but I'm not sure how to present it in a GUI and what the use-case would be.

OK, we'll see if there is a use case.

> > It's not really clear how "a tab in settings for managing default options" would work.
> 
> I was thinking maybe something like this: http://imgur.com/UfaVXSc

OK. So this is for the admin in order to manage templates. Not sure if I see the use case for download and upload. For users it seems more appropriate if they could first load a template, then change the options and then store them again, possibly overwriting the loaded template. I'm not sure if admins should have a separate interface from normal users.

**Comment by josteinaj** [comment]
> For users it seems more appropriate if they could first load a template, then change the options and then store them again, possibly overwriting the loaded template.

Good idea! That's probably a better way of editing templates than the download+upload path.

So maybe all the template management stuff should happen through a single widget in the job creation form then. Letting you load, delete, add and overwrite templates in a list. A toggle control can select whether the template is user-specific or global.

**Comment by bertfrees** [comment]
The single widget could work. We should be careful not to overwhelm the user with complex widgets. If deleting and renaming is not required, it could look really simple. Let's make some more drawings first.

**Comment by josteinaj** [comment]
Agreed

**Comment by josteinaj** [comment]
It could also be useful to set a default template; so that whenever you pick a script, the options and inputs are automatically filled out.

**Comment by bertfrees** [comment]
OK

**Comment by josteinaj** [comment]
Updated bullet list in issue description.

**Comment by josteinaj** [comment]
Added "Related issues" list.

**Comment by josteinaj** [comment]
I created a repository called `pipeline-jobs-java`. @rdeltour I requested transferring the ownership to you since I don't have permission to transfer it to the daisy org. Could you move it to the daisy org?

**Comment by bertfrees** [comment]
I think most check boxes can be ticked off?

**Comment by josteinaj** [comment]
Yes, most checkboxes are done. The remaining I think we can ignore for now.

@rdeltour the https://github.com/daisy/pipeline-jobs-java repo can be deleted if you want; everything is in clientlib-java now.
