### ISSUE TITLE
EPUBs validation on generation

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline-tasks#132]
As we talked a while back, i think it could be useful to have a validation pass done by epubcheck of the epubs generated by the pipeline, either optionnaly or systematically.

It should be possible to have a systematic non-blocking epubcheck test after or before the px:epub3-ocf-zip step while the epub is stored on disk (see [store.xpl](https://github.com/daisy/pipeline/blob/master/modules/scripts-utils/epub3-ocf-utils/src/main/resources/xml/xproc/store.xpl)), with the html report stored aside the resulting epub.

What do you think ?

(I'll add a commit referencing the issue and a first proposal of modification on a new task/ branch)

**Comment by bertfrees** [comment]
The idea is good, but I would at least make it possible to skip the validation.

My only reservation about this is that we're just combining two simple steps into a single step, without adding much additional functionality (an example of extra functionality would be if certain action were required depending on the outcome of the validation), which doesn't make it that much more useful than when you would have to call the steps separately. Such utility steps can be useful but also have a downside: they are less flexible than the individual steps unless you make all the options of both steps available on the combining step, which could cause some maintenance overhead. If it's obvious that two steps belong together, it's a no-brainer. But if it's not that obvious, like in this case (there are enough situations when you want to validate an EPUB without storing it, or when you want to store it without validating it), I'm a bit more careful.

@rdeltour Your opinion?

**Comment by bertfrees** [comment]
By the way these kind of issues shouldn't go in pipeline-tasks. pipeline-tasks is used for managing planned tasks. @rdeltour can you move it to pipeine or pipeline-modules?

**Comment by NPavie** [comment]
Since i'm not sure @rdeltour can close it, I'm closing the issue following previous discussion :)
