### ISSUE TITLE
Prepare v1.8.1 bug fix release

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#14]
@capitancambio here you go. Can you please reference the PR you wanted included in this milestone ?

**Comment by capitancambio** [comment]
There are things to be done for this release:
1. Make sure that the it passes on windows.
https://github.com/daisy/pipeline-framework/pull/62
https://github.com/daisy/pipeline-framework/pull/64
https://github.com/daisy/pipeline-assembly/pull/46
1. Solve some issues with the relax ng schemas
   https://github.com/daisy/pipeline-framework/pull/63
2. Make the windows installer clean the previous data folder
   https://github.com/daisy/pipeline-assembly/pull/48

**Comment by capitancambio** [comment]
@rdeltour  this should do trick, I can't get it ready if you explain me the common procedure :wink:

**Comment by rdeltour** [comment]
@capitancambio I merged all PRs. I'm wondering though if we should release 1.8.1 if we've not fixed the issue we had with launching the Pipeline under Java 8. This will have people complain again. Do you think you can have a look ?

**Comment by capitancambio** [comment]
Sure I'll take a look into that

cheers,

Javi
