### ISSUE TITLE
Select TTS voices based on user-preferences and document languages

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#18]
TBD:
- review the existing voice-setting mechanism
- see if UIs can easily piggy-back their own voice selection on the existing mechanism (e.g. aural stylesheets)

**Comment by rom1mouret** [comment]
Some details regarding the UI:
- As the content of aural CSS stylesheets are format-dependent, selecting voices from the UI would require to generate different pieces of CSS for every possible input format, unless there exists a generic CSS selector which I am not aware of.
  It is certainly more convenient to customize the main voice via a new script option. Such an option would have the same effect as CSS inlining, i.e. it would add customization attributes to the SSML sentences.
- Although the TTS services do expose a method that returns a list of available voices, this method is currently called within a safe context. In particular, the TTS resources must be initialized before this method is called and must be freed eventually. So, beware that using this feature out of its usual scope may involve a bit of trickery.

**Comment by josteinaj** [comment]
I'm concerned about the complexity of requiring each UI implementation to implement this. The Web UI and GUI could share a Java library for this, but the CLI would need a separate implementation. If we decide in the future to for instance reimplement the Web UI using JavaScript, that would be a third implementation.

And if we go the same route for other types of dynamic enumerations, for instance braille settings, selecting audio encoders, and anything else we haven't though of yet, each UI would have to implement these things separately.

What was the main reason again we wanted this to be implemented in the UI instead of in the engine and exposed through the API?

**Comment by rom1mouret** [comment]
My preference goes to adding this to the Framework API, regardless of whether we decide to postpone the webservice counterpart.

More details about what I called a "safe context" in which the voice enumeration must be called for now:
- Very roughly, a semaphore prevents the pipeline from opening too many TTS contexts simultaneously, and the voice enumeration is one the feature that is accessible from such a context. But I'm sure I'll find a workaround for that.
- I am more concerned with the second issue: the TTS processors require some settings before enumerating the voices. For instance, Acapela requires the list of Acapela's server IPs and a sample rate (a bit weird I know). These two options can be put in the system properties, but I prefer them to be dynamic options of our conversion scripts thanks to the main TTS config file, e.g. you can run two scripts with different Acapela servers. Then, ideally, the UI should ask users to configure the server IPs prior to retrieving the list of voices, in a manner that is not warranted to be consistent with the options of the next conversion scripts, unless the UI doesn't let the users change all the script options. Or, alternatively, the script options are chosen prior to the voice selection, which implies that voices must be selected again for every change of the options.

**Comment by rdeltour** [comment]
For v1.9, this task is closed with the features enabled with user-provided aural CSS.
Further API and UX improvements, such as discussed in the [Nancy F2F](https://docs.google.com/document/d/1JXBLzXr3WldLiNDkmZd7gdGITuZyLAgeddf7gO9lQbY/edit#) will be described and developed in other tasks.
