### ISSUE TITLE
HTML to XHTML5 rewrite

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#2]
he current HTML to XHTML5 transformation is based on an XSLT generated from a
list of changed elements.
It should be rewritten manually, to be more easily readable and maintainable.

Can be based on the [Differences from HTML4](http://www.w3.org/TR/html5-diff/) and [Elements of HTML](http://rawgit.com/w3c/elements-of-html/master/index.html) documents

**Comment by josteinaj** [comment]
### html-utils
- [ ] rewrite the html5 upgrade stylesheet: daisy/pipeline-issues#315
