### ISSUE TITLE
Start the Pipeline engine as a service

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#20]
TBD
- review if this is needed, or would be beneficial
- how to do it on Windows ? (e.g. JSW)
- how to do it on Mac ?
- how to do it on Linux ?

**Comment by josteinaj** [comment]
As a use-case; we have a few Pipeline 2 servers in our park at this point for different purposes (all running on linux). If the servers have to be restarted for whatever purpose (moving a server, power outage, etc.), I have to ssh into the server and start the pipeline 2 engine + webui. If I'm not available, someone else has to follow some instructions I've written for starting each server properly. It would be great to instead have it set up as a service that automatically starts when the server turns on.

**Comment by bertfrees** [comment]
@josteinaj If you're on Debian, the Debian package of the server already has a service which you could use. A package+service for the user interface is also planned.

**Comment by josteinaj** [comment]
Aha, cool, I'll give it a try when I get the time. Debian-derivative Ubuntu is ok I presume?

**Comment by rdeltour** [comment]
Experiments based on YAJSW seem to work OK on Windows, and on Linux we can use the Debian package.

Closing this task, since we decided during the Dec 2014 f2f that we don't have a strong need for this feature as it doesn't make a big difference for usability and it's not worth the cost.
