### ISSUE TITLE
Use Felix SCR annotations for generating the scr:component XML files

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#22]
Is there a reason we're not doing that now?

http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/scr-annotations.html

**Comment by rdeltour** [comment]
:+1:

I've been wanting to do that for a while, just not spent the time. Lat time I had a look I was thinking of using bnd annotations, which I think is roughly equivalent to SCR annotations, maybe a bit more close to OSGi DS semantics (not sure).

**Comment by bertfrees** [comment]
OK, I'll take the first steps then :)

Bnd annotations are not completely compatible with the ones from Felix (there's also the standard OSGi ones by the way). I thought by using Felix  annotations we would have a higher chance it would work with the Maven plugin, but haven't actually tried.

**Comment by rdeltour** [comment]
We're using the `maven-bundle-plugin`, which is based on bnd under the hood and understands bnd annotations out of the box (as far as I remember), that's why I was thinking of using those. But if you think otherwise, go ahead, I don't mind much.

**Comment by bertfrees** [comment]
I'll try Bnd first.

**Comment by rdeltour** [comment]
btw, aren't annotations standardized by OSGi now ? If yes we should try to use "standard" OSGi annotations.

**Comment by rdeltour** [comment]
this [blog post](http://kishanthan.wordpress.com/2014/03/29/using-annotation-with-osgi-declarative-services/) explains how to use it with the Maven Bundle Plugin.

**Comment by bertfrees** [comment]
thnx!

**Comment by bertfrees** [comment]
Standard OSGi annotations work, but we need to update to org.osgi.compendium 4.3.0 and maven-bundle-plugin 2.5.0

**Comment by rdeltour** [comment]
> we need to update to org.osgi.compendium 4.3.0 and maven-bundle-plugin 2.5.0

sounds OK to me (post v1.9 of course)

**Comment by bertfrees** [comment]
I am using annotations now in most braille modules.

**Comment by bertfrees** [comment]
This is done, but is on a local branch. I think it will be easier to merge this after https://github.com/daisy/pipeline-tasks/issues/31 has been merged.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-framework/pull/134

**Comment by bertfrees** [comment]
Done
