### ISSUE TITLE
Add OSGi runtime dependencies to all POMs

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#23]
Like I have done in the Braille modules. This was important to simplify the POMs that have integration tests. It allowed me to drop the transitive dependencies from the POMs, as they are now automatically put on the test classpath.

**Comment by bertfrees** [comment]
see https://github.com/snaekobbi/pipeline-mod-braille/commit/0bbf2d4b17b58caa27538ff5069eb3bb4a0fb692

**Comment by bertfrees** [comment]
Is now after release 1.9 a good time to start doing this?

**Comment by rdeltour** [comment]
@bertfrees yes, go ahead!

**Comment by bertfrees** [comment]
Does it look okay?

**Comment by rdeltour** [comment]
I've not looked at all the semver details, but the approach LGTM.
Can you create PRs assigned to me when ready to merge?
