### ISSUE TITLE
Copy non-XML resources located inside bundles

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline-tasks#24]
In XProc, is there any way to copy non-XML resources from inside a bundle? Ideally via px:fileset-store.

If not, it should be doable by providing our own implementation of px:copy that can handle URL such as `bundle://2.0:2/fallback-sound.mp3`, right?

It can come in handy to use default images or default mp3 files.

**Comment by bertfrees** [comment]
We already have a step for this, I believe it is called `px:copy-resource`. Not sure if `px:fileset-store` uses it.

**Comment by rom1mouret** [comment]
Thanks. That's what I was looking for.
