### ISSUE TITLE
Make it easier to run XProc and XSLT components in other environments (outside of Pipeline)

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#28]
Our XProc and XSLT components are specific to the Pipeline mainly because of the custom URI resolving and custom Java XPath functions and XProc steps. Currently, in order make the components work outside of the Pipeline framework, you have to include a big list of dependencies, while all that is really required is a small piece of code that configures Saxon/Calabash to use the custom URIResolver and the custom Java functions/steps.

**Comment by rdeltour** [comment]
I agree there's room for improvement here. Any idea how to get things better?

**Comment by bertfrees** [comment]
We were planning to just try to use a Pipeline component in another context, see what kind of problems we stumble upon, and then try to fix them. Maybe the parts from calabash-adapter and modules-registry that take care of the Saxon/Calabash configuration can go in smaller jars that don't depend on other Pipeline modules, and maybe we can try to get it working without OSGi.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-tasks/issues/31 and https://github.com/daisy/pipeline-tasks/issues/33.

**Comment by bertfrees** [comment]
Fixed in https://github.com/daisy/pipeline-framework/pull/134 and https://github.com/daisy/pipeline-build-utils/pull/50

**Comment by bertfrees** [comment]
Done
