### ISSUE TITLE
Create aggregator projects

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#34]
or "super projects": repositories that include the source code of several sub-repositories. This should make it easier to branch, build or release several repositories at once.
- The problem with branching several repos is that you rely on snapshot dependencies across repositories, so you have to be very careful that you are building against the right snapshots.
- The problem with releasing a lot of repos is that is takes a lot of time.
- A general problem with a lot of repos is that it is hard for newcomers or occasional contributors to know where to start.

We are definitely not the only ones that feel the need for aggregating repositories. There are at least a dozen "git submodule" variants. I've looked into some of them and I think [git-suprepo](https://github.com/ingydotnet/git-subrepo) could be a good solution for us. I'm gonna play around with it a bit.

**Comment by josteinaj** [comment]
`git-subrepo` looks pretty good from its description.

**Comment by bertfrees** [comment]
See https://github.com/snaekobbi/pipeline.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline. I think I can close now.
