### ISSUE TITLE
Create a web site

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#5]
Initial version s/b focused on end-user documentation + general developer guides.

**Comment by bertfrees** [comment]
We would really like to have a website for our project, either use the official Pipeline website or clone and modify it. Is there some code available I can try?

**Comment by rdeltour** [comment]
@bertfrees I'm horribly late on this, local code I have is not ready to be published. Do you have a deadline?

**Comment by bertfrees** [comment]
There's no deadline. But initially it's mainly intended for the developers, and it would be good if we could work on the developer documentation while developing. Just being able to look at the code that builds/assembles the docs, and play with it locally, would already be useful I think. If it's not ready to be published we won't publish it. You had something that you demo'd in Paris that already looked quite good.

**Comment by bertfrees** [comment]
The prototype can be seen on http://daisy.github.io/pipeline.

I will also push the code soon: https://github.com/daisy/pipeline/tree/website.

We are ready now for porting the old documentation on the google wiki, updating it, adding new pages, etc.: see issue https://github.com/daisy/pipeline-tasks/issues/35

**Comment by bertfrees** [comment]
Can be closed?
