### ISSUE TITLE
Documentation: html-to-dtbook

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#61]
- [ ] Generic page with synopsis
- [ ] Fix in-script documentation so that synopsis looks right
- [ ] Add more text to Markdown file

Result: http://daisy.github.io/pipeline/modules/html-to-dtbook

**Comment by bertfrees** [comment]
Anyone: why did we remove this script from the assembly?

**Comment by bertfrees** [comment]
- [ ] To do: add author metadata to script.

According to git log it was Jostein and Romain who worked on the script. Shall I put you both as author (in that order)?

**Comment by josteinaj** [comment]
This script is something I imported and based on the xhtml2dtbook script in Pipeline 1, so the main author should be whoever wrote that one. I'm guessing it was @rdeltour who wrote the original script? The script hasn't been tested very much.

**Comment by rdeltour** [comment]
> I'm guessing it was @rdeltour who wrote the original script?

No, as far as I remember this script actually precedes my arrival to the Pipeline project ;-)
Its primary shortcoming is that the accepted input XHTML is **heavily constrained**. It is fairly well documented in Pipeline1, but used to be a tad confusing for end users.

**Comment by bertfrees** [comment]
Should we port the Pipeline 1 documentation you think?

**Comment by rdeltour** [comment]
If we keep the script, yes. But I'm not sure there is a demand. @josteinaj do you use it at NLB?

**Comment by josteinaj** [comment]
I think I have a copy that I use for some internal scripts, but it's just a copy of the XSLT. So we don't need that script as an official script, no.

**Comment by bertfrees** [comment]
@rdeltour Let's remove it. We can always conjure it up again if we want. OK?

**Comment by bertfrees** [comment]
Module was deleted in https://github.com/daisy/pipeline-scripts/commit/63c84b4.
