### ISSUE TITLE
Identify stability issues

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#84]
## March
- [x] [launch-time issue for SBS/Nordic countries (using the braille modules)](https://github.com/daisy/pipeline-mod-braille/issues/135) (@bertfrees)

## Later
- [ ] launch-time issue from the Tobi team: try to reproduce + create GH issue (@marisademeglio)
- [ ] [logging related errors at launch-time](https://github.com/daisy/pipeline-assembly/issues/104)

**Comment by bertfrees** [comment]
SBS's launch-time issue seems to have been fixed by updating to a newer version of Felix. It does not fix the logging related errors though. I don't know about Tobi's launch-time issue.

**Comment by bertfrees** [comment]
I'm going to create a PR with what I have so far and then move the issue to the next milestone.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-assembly/pull/130

**Comment by bertfrees** [comment]
> [logging related errors at launch-time](https://github.com/daisy/pipeline-assembly/issues/104)

The reason I'm deferring this one is because I've already spent a lot of time on it without result and don't know how to proceed. I'm hoping it will go away by itself when we [have made OSGi optional](https://github.com/daisy/pipeline-tasks/issues/73).

**Comment by rdeltour** [comment]
Closing this one. We can track the "later" items separately

**Comment by rdeltour** [comment]
So we already had daisy/pipeline-assembly#104 and I just created daisy/pipeline#513. @bertfrees is it OK or do you think we should also have something here in `pipeline-tasks`?

**Comment by bertfrees** [comment]
OK, I guess that's fine until we actually put it in the planning again.
