### ISSUE TITLE
Improve build speed

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#86]
- [x] [ready] XProcSpec optimization ![XS][]

[XS]: http://daisy.github.io/pipeline-tasks/XS.svg "Extra small (1 hour - 2 hours)"
[S]: http://daisy.github.io/pipeline-tasks/S.svg "Small (2 hours - 1 day)"
[M]: http://daisy.github.io/pipeline-tasks/M.svg "Medium (1 day - 2 days)"
[L]: http://daisy.github.io/pipeline-tasks/L.svg "Large (2 days - 1 week)"
[XL]: http://daisy.github.io/pipeline-tasks/XL.svg "Extra large (1 week - 2 weeks)"
[XXL]: http://daisy.github.io/pipeline-tasks/XXL.svg "Extra extra large (2 weeks - 1 month)"

**Comment by bertfrees** [comment]
See PRs:
- https://github.com/daisy/xproc-maven-plugin/pull/18
- https://github.com/daisy/pipeline-mod-braille/pull/142
