### ISSUE TITLE
Create a minimalist GUI

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#9]
### Features /requirements
- split view: list of jobs | detailed view
- details view:
  - for a new job: form to create a new job
  - running job: what's the status, what's going on
  - completed job: access log, get the results (download the result, open a viewer, etc)

Out of scope:
- see the results in the GUI

**Comment by josteinaj** [comment]
This will replace the desktop version of the Web UI, right? So when the minimalist GUI is released, I can remove all the "desktop mode" stuff from the Web UI? Is the GUI scheduled for v1.8 (end of May) or v1.9 (in other words; can I start stripping away the desktop stuff from the Web UI already)?

**Comment by rdeltour** [comment]
Yes, this will replace the desktop Web UI. It’s not planned for 1.8 though. A first version is planned for the October milestone.

**Comment by josteinaj** [comment]
Ok. I'll make sure the desktop Web UI is working for 1.8 then.

**Comment by bertfrees** [comment]
Can be closed?
