### ISSUE TITLE
update URI is not found

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-tasks#97]
**[issue should be moved to daisy/pipeline]**

The system properties file says
org.pipeline.updater.updateSite=http://daisy.github.io/pipeline-assembly/releases/

which gives a 404 not found

The updater GUI says not found (I'm guessing it uses this same property URI value):
https://slack-files.com/T064GC3F1-F4FN9HZ6U-977f5bb302

**Comment by josteinaj** [comment]
The updater should fetch `${updateSite}/current`, which should not give a 404.

At least this works for me:

http://daisy.github.io/pipeline-assembly/releases/current

**Comment by marisademeglio** [comment]
@josteinaj does the updater gui work for you? i had been trying the 1.10 release version.

also, do you know where in the updater code it uses this URI? I see this:
https://github.com/daisy/pipeline-updater/blob/master/updater.go#L83

but I don't know if that's the right/only place.

**Comment by josteinaj** [comment]
Yeah, that's what I saw too, and judging from a quick browse through the gui updater code it seems that the gui also uses the updater cli indirectly?

I'll try and see if the 1.10 version works for me, I haven't actually tried...

**Comment by josteinaj** [comment]
Yes it seems to work for me. I get: "INFO There are no new versions".

edit: using linux zip version and running with `bin/pipeline2 gui` btw, in case it matters

**Comment by marisademeglio** [comment]
It works for me on macOS -- I see the same as you -- but not on windows (updater says 404 as in the screenshot attached to issue).

**Comment by marisademeglio** [comment]
it looks like on windows, the updater is a separate program, whereas on mac and linux, it's built in to the main pipeline gui. 

the pipeline-gui updater pane (accessed from the gui menu on mac and linux) refers to org.daisy.pipeline.updater, which does seem to append 'current':
https://github.com/daisy/pipeline-framework/blob/master/updater-wrapper/src/main/java/org/daisy/pipeline/updater/Updater.java#L31

but the windows standalone updater just uses the same pane:
https://github.com/daisy/pipeline-updater-gui/blob/master/src/main/java/org/daisy/pipeline/updater/gui/MainWindow.java#L25

and then it looks like this pane calls the framework's updater java package, which calls the updater golang cli program. 

so i'm not seeing the difference, codewise, between windows and other OSes.

**Comment by bertfrees** [comment]
How exactly do you launch the standalone updater on Windows? When I just execute the (win32) pipeline-updater-gui.exe file I get nothing at all.

**Comment by bertfrees** [comment]
OK I was able to reproduce the error.

**Comment by bertfrees** [comment]
It just turned out to be a version mismatch. The standalone updater GUI was still using version 1.0.0 of updater-wrapper which used "latest" instead of "current".

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/pipeline-updater-gui/pull/1
