### ISSUE TITLE
Lightweight version of Pipeline

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#99]
Essentially, a "Pipeline Lite 2". In practice, this means:

- No persistent storage
- No webservice, only the Java API. This also means no OSGi and launch script.

The Tobi team would be very interested in this for example. They use it as a 3d party process from Tobi/Obi at import/export time, so the lighter it is, the better. (To do: check whether they would like to use the Java API or continue using web API.)

Related: https://github.com/daisy/pipeline-tasks/issues/73.

**Comment by bertfrees** [comment]
Build options were added in version 1.14.5 of pipeline-assembly to omit the web service, persistence, GUI and OSGi.

**Comment by josteinaj** [comment]
This sounds great! Is there, or will there be, a release of this?

**Comment by bertfrees** [comment]
It has been supported in the build script since release 1.14.5 (March 2022).

If you mean "will there be a download available?": that doesn't really make sense because it depends on people's use case (how they want to launch Pipeline and how they want to interact with it) which components are needed.

**Comment by josteinaj** [comment]
> If you mean "will there be a download available?"

Yes, that's what I meant.

Ok, yeah I guess that makes sense.
